### ISSUE TITLE
Wireframe comments

### ISSUE THREAD

**Issue by kindly** [open-contracting/extension-explorer#1]
An intital wireframe of how a core extensions may look can be found in: 

https://open-contracting.github.io/extension-explorer/wireframes/core_extension_0.html
(the fonts are not working due to limitations in typekit)

**Comment by kindly** [comment]
Few initial points

- Language navigation has not been added yet but will likely be like the standard docs in lower left
- Navigation of community extension versions can be on the right instead of on the left as it will be different for each extension.
- Left side navigation will probably scroll separately.
- Core and community extension completely seperate
- Homepage may have a list of most up to date core and community extensions in tabular form replicating behaviour of http://standard.open-contracting.org/latest/en/extensions/#using-extensions

**Comment by jpmckinney** [comment]
This is feedback on the one page wireframe above, but I expect we will also do iterations on the wireframes (or paper prototypes, etc.) of the other pages. I'm not clear on the exact proposal for the homepage and community extension versions; those can be discussed once a paper prototype or wireframe has been prepared.

Context to account for:

* Presently, for any version of a core extension, all other core extensions have a version with the same name. However, it's not guaranteed that this will always be true, e.g. if we author OCDS 1.1.4 and only one core extension has changed, we wouldn't necessarily roll all core extensions to 1.1.4.
* While we presently wait for a new version of OCDS to release new versions of core extensions, it may be that, as OCDS becomes more stable, we will release updates to core extensions separately, possibly using a versioning scheme that doesn't match OCDS version numbers.
* If an implementer targeted OCDS 1.1.1, they should nonetheless be strongly encouraged to use the latest patch version of core extensions, within the same minor version series, because the latest patch version (e.g. v1.1.3 of several core extensions) may contain important bug fixes.

Feedback based on above context:

* Instead of giving equal access to all versions of core extensions, the latest patch version within every minor series (only 1.1 at this time) should be prioritized, and it should be deliberately harder to access the documentation of older patch versions (e.g. having to click through an extension's 'older versions' navigation). Since the only minor series with extensions at this time is 1.1, we may want to omit that navigational element until we have another minor series.

Other non-exhaustive feedback:

* We should have a search box in the main navigation. Search may be implemented in a later iteration, but we can still consider where the box will be at this time.
* Best practice seems to be to put language selection in the top-right (for left-to-right languages). A belt-and-suspenders approach would also list languages in the footer.
* We may want quick access to the extension's declaration to be a block above the docs, instead of a tab. e.g. [PyPi](https://pypi.org/project/ocdsmerge/) puts the pip command at the top of the page, [RubyGems](https://rubygems.org/gems/rails) puts it in a sidebar, etc. If the "How to Use" content will be the same for all extensions with the exception of the extension's declaration, we may want the generic content to be a page accessible from the top-navigation, rather than each extension.
* It's possible we'd want to generate a table of contents based on Markdown headings, for easier access to parts of the document, especially as the trend is towards longer documentation for core extensions. We would need to place this TOC somewhere.
* I'm not sure that navigating between the documentation of different extensions is such a common task that it should take a primary position as sticky left-hand sidebar. I figure that navigating between sections of an extension's documentation (if we implement a TOC) and navigating between an extension's docs, schema, codelists, and examples will be much more common tasks. Presently, the latter task would require scrolling back up to the top of the page. I would be interested in seeing an iteration on the wireframes in which this navigation is in the left-hand sidebar.
* If we remove the list of extensions from the left sidebar based on above comment, then we may want to implement a breadcrumb, to make it easy to return to the list of extensions. A breadcrumb also provides context to users who may access an extension page using a direct link, and may not have had the experience of clicking the main navigation links to get to the lists of extensions.
* I haven't reviewed the user stories, but please ensure the stories are accounted for in the wireframes.

**Comment by jpmckinney** [comment]
Anyhow, I think there are enough content blocks on which we have agreement that implementation can start on those. Sorting out where those ought to appear on the page can be done independently.

**Comment by kindly** [comment]
Added some more wireframes:

An alternative version of a core extensions page based on @jpmckinney comments: 
https://open-contracting.github.io/extension-explorer/wireframes/core_extension_1.html

A very rough version of the homepage:
https://open-contracting.github.io/extension-explorer/wireframes/home_0.html

An example of the core extensions listings page:
https://open-contracting.github.io/extension-explorer/wireframes/core_0.html
This is probably very similar to the community extensions one.

Also I would like to discuss the possibility of making a separate page for selecting what extension you want in your data and not having as part off the other pages interface, however this is not done yet but will likely be very similar to:
http://standard.open-contracting.org/1.1-dev-new-search/en/extensions/#using-extensions

**Comment by jpmckinney** [comment]
Homepage:

* The top-navigation is repetitive with the page content. This page can have a different navigational layout than other pages.
* This page could benefit from some design work, perhaps creative use of color or icons/images, to make it look smart and professional.

List page:

* Should we integrate the extension's category?
* How do the version links work? Does "1.1" go to the latest patch version within the 1.1 series?
* I'm not sure that the grid layout is best. Once we have real descriptions, the blocks will be of different heights, and a user's eyes will have to dart all over the screen to read all the extension names. Having a one-column layout with all headings aligned seems simpler and faster for users scanning names. If we're concerned about the difficulty of reading long lines of text, we can use a fixed-width layout.
* We can omit the compatibility for now, as everything is only compatible with 1.1.

Extension page:

* We should have code highlighting for JSON blocks.
* I'm not sure of the placement of the version switcher, which seems arbitrary. It may be better to have it closer to the extension name; a designer might have an opinion on information hierarchy.
* "Extensions info" in the sidebar occupies a lot of space, considering the info it links to will be very brief. That info could maybe be integrated below the extension name and description.
* The color for code tags clashes with the green. A designer might have suggestions. We may want a designer to recommend a palette, as I also found the green links to be a bit hard on the eyes.

A page for selecting extensions sounds good.

**Comment by odscjames** [comment]
> We can omit the compatibility for now, as everything is only compatible with 1.1.

https://github.com/open-contracting/ocds_enquiry_extension/blob/v1.1.3/extension.json ? 😄 

Also maybe good to have now to:
- make compatibility explicitly clear to new readers who don't know that
- establish that as a UI/data/code norm for later

**Comment by jpmckinney** [comment]
If we want to make compatibility part of the UI now, then we need to address use cases like:

* If you have 2.0 data, then you typically want to see extensions that are compatible with 2.0 as a primary task, and then maybe see whatever other extensions exist as a secondary task.
* If you're implementing OCDS, then you probably don't care to know all the versions with which an extension is compatible – only that it's compatible with the version you're implementing.

So, there are details to work out in terms of what order to present extensions, and how to present a given extensions' compatibilities. Since we don't need to solve these UI issues (in addition to other issues), I figure easiest to postpone.

**Comment by robredpath** [comment]
Closing this issue as feedback is being incorporated into first version of interface. Further comments welcome against the work!

**Comment by jpmckinney** [comment]
Just to follow-up to my earlier comment: I realized that compatibility is related to a version of an extension – not the extension itself as the earlier mockups might suggest – so we'll need to communicate that clearly when compatibility is integrated.
