### ISSUE TITLE
Initial technical choices.

### ISSUE THREAD

**Issue by kindly** [open-contracting/extension-explorer#2]
Discussion on how we implement the website.

**Comment by kindly** [comment]
Depends very much on the outcome of this issue:
https://github.com/open-contracting/extensions-data-collector/issues/11

If internationalization or sphinx directives are needed to be resolved by the extension explorer website itself then sphinx should be considered.
However, as this is not a documentation website itself and will be used for rendering a website based on docs from elsewhere using sphinx seems like a difficult solution, this is because:

- We would have to pull markdown files from elsewhere into a specific tree structure that would suit the navigation of the site.
- navigation more complicated that normal docs site with versioning/languages.  This is done by standard website mostly by Apache configuration currently and not dynamically.
- toc directives may need to be rewritten on generated by external code.
- Most pages would likely need to be generated before sphinx renders it to add certain headers or context.
- i18n will be complicated as some translations will come from outside and some from the site itself.


If sphinx on this website was not needed for rendering then I would prefer [frozen-flask](https://pythonhosted.org/Frozen-Flask/) as an alternative.  This is because navigation would be a lot easier and I feel it would be a lot more easy to work on as it would be more like working on a normal MVC site.
A little sample of how navigation would work would be:
https://github.com/open-contracting/extension-explorer/blob/gh-pages/extension_explorer/__init__.py

**Comment by jpmckinney** [comment]
As on call, I agree that an alternative to Sphinx is preferred.

Among alternatives, there are many that assume you are authoring all the content in the site (rather than pulling it from other sources) and therefore have greater control over the content files. For example, Jekyll, Pelican, Nikola, etc. require [Front Matter](https://jekyllrb.com/docs/frontmatter/) or similar to configure page titles, layouts, etc. which would have to be injected into our Markdown files – which is undesirable. Others make heavier use of Jinja2 tags (e.g. Lektor) to configure layout, which would also require injection.

Then, there's frozen-flask, which wouldn't require such injection. I tried to find others with a similar approach to compare, but a quick search didn't turn anything up. So, happy to go with frozen-flask.

**Comment by jpmckinney** [comment]
I figure we should rename this issue to e.g. choice of framework, as 'technical implementation' could be a never-closed issue.
