### ISSUE TITLE
Schema: View extended schema

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension-explorer#22]
On our call earlier this week, @duncandewhurst mentioned regularly using the [docson schema viewer](http://standard.open-contracting.org/latest/en/schema/release/) when interpreting the schema.

Being able to view a copy of the schema with any set of extensions applied would potentially by very useful indeed. 

**Implementation**
An ideal implementation might allow that:

* A user can see in docson which fields have been added by the extension, possibly by virtue of colour coding;

* This is visible as part of each individual extension page;

* It is possible from the extension selector to explore what the schema will look like with a collection of extensions applied to it;

**Issues to consider**

* We may need the ability to see how the extension looks against different versions of OCDS in future (an MVP could merge just against 1.1, but when 1.2 is out, would need to cover both)

**Possible implementation approach**

I believe we have modified docson in the past and found that possible, so I'd be thinking that we have a process that:

* Grabs the extension schema; 
* Modifies this to insert some property to each object or rifled in the extension to include the name of the extension, and a flag that this is an extended field;
* Merge this into the OCDS schema;
* Update docson so that it outputs class information about the presence of an 'isExtended' flag in each object/field, and the name of the extension;
* Update CSS so that this shows up

**Comment by jpmckinney** [comment]
I agree that being able to view a patched schema would be useful: it shows the change in context, and relieves the user of having to have a lot of information in their head when viewing the patch on its own.

In terms of whether we use Docson or not – I'm not sure that Docson is the best tool. There's been confusion about the way it presents `format`, `enum`, etc. which we've done some work to address, but it may be quicker/easier to build something new that we can more easily modify.

**Comment by jpmckinney** [comment]
The schema page of each extension has been much improved since this issue was authored, with a link to the object being extended. We can re-open if there is any new demand (or user research suggesting this improvement).

**Comment by duncandewhurst** [comment]
Personally, I don't find the schema tables to be the most intuitive way to understand the schema. So whilst the improvements are good, they don't really address this issue, which was about displaying a patched schema.

I'm not sure whether other users also find the schema browser easier to work with.

To understand the demand from internal users we could ask the helpdesk analysts for their views.

For external users, do we have any analytics which could show us whether the schema reference tables or the schema browser are most commonly visited in the main standard docs?

**Comment by jpmckinney** [comment]
Sure, we can add a browser as an additional means to understand the extension.

In the OCDS documentation, the stats are roughly 2:1 for visits to the tables versus Docson, and time on page is also 2:1. Taken together, that's 4:1 in terms of time spent.

The tables make it easy to search within page; unless you already know where to look, you can spend a lot of time clicking to expand sections in Docson. We'd need to not only highlight the new field as in the issue description, but all its parents, so that users can follow the trail.

Several users find the annotations (for type, pattern, cardinality, etc.) in Docson to be confusing (open-contracting/standard#573, open-contracting/standard#882, open-contracting/standard#1006).

If a user is trying to understand what an extension is adding, it's easier to see a few tables with a couple rows of just the new fields, than to browse the OCDS schema as a whole (it's more work to find what's new, even if we highlight the trail as above).

Also noting that the tables in the Extension Explorer are not the same as in the OCDS documentation (they have been improved).

**Comment by duncandewhurst** [comment]
Great, it's good to see the stats. Given the tables are more popular, I'm happy for this to be closed.

**Comment by jpmckinney** [comment]
Sounds good – happy to re-open if we hear new feedback on how people prefer to explore the schema.
